---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kaptain-helm-repo
  namespace: kommander-flux
spec:
  url: "https://mesosphere.github.io/kaptain-charts"
  interval: 10m
  timeout: 1m