---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kaptain-helm-repo
  namespace: kommander-flux
spec:
  url: "http://kaptain-helm-mirror.kommander.svc"
  interval: 10m
  timeout: 1m
