---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kaptain-helm-repo
  namespace: kommander-flux
  labels:
    kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: "${helmMirrorURL:=http://kaptain-helm-mirror.kaptain-n449m-bbggl.svc}"
  interval: 10m
  timeout: 1m
