apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kaptain
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kaptain
      sourceRef:
        kind: HelmRepository
        name: kaptain-helm-repo
        namespace: kommander-flux
      version: 2.0.0-dev
  interval: 15s
  timeout: 20m
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  releaseName: kaptain
  values:
    global:
      workspace: ${releaseNamespace}
  valuesFrom:
    - kind: ConfigMap
      name: kaptain-2.0.0-defaults
