apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kaptain
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kaptain
      sourceRef:
        kind: HelmRepository
        name: kaptain-helm-repo
        namespace: kommander-flux
      version: 2.2.0
  interval: 15s
  timeout: 20m
  install:
    remediation:
      retries: 30
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 30
    crds: CreateReplace
  releaseName: kaptain
  valuesFrom:
    - kind: ConfigMap
      name: kaptain-2.2.0-defaults
